'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("37")>  _
        Public Property Desert_Eagle_SkinID() As Integer
            Get
                Return CType(Me("Desert_Eagle_SkinID"),Integer)
            End Get
            Set
                Me("Desert_Eagle_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blazing Hot")>  _
        Public Property Desert_Eagle_SkinName() As String
            Get
                Return CType(Me("Desert_Eagle_SkinName"),String)
            End Get
            Set
                Me("Desert_Eagle_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("658")>  _
        Public Property Dual_Berettas_SkinID() As Integer
            Get
                Return CType(Me("Dual_Berettas_SkinID"),Integer)
            End Get
            Set
                Me("Dual_Berettas_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Snake Attack")>  _
        Public Property Dual_Berettas_SkinName() As String
            Get
                Return CType(Me("Dual_Berettas_SkinName"),String)
            End Get
            Set
                Me("Dual_Berettas_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("660")>  _
        Public Property Five_Seven_SkinID() As Integer
            Get
                Return CType(Me("Five_Seven_SkinID"),Integer)
            End Get
            Set
                Me("Five_Seven_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Beastmode")>  _
        Public Property Five_Seven_SkinName() As String
            Get
                Return CType(Me("Five_Seven_SkinName"),String)
            End Get
            Set
                Me("Five_Seven_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("38")>  _
        Public Property Glock_18_SkinID() As Integer
            Get
                Return CType(Me("Glock_18_SkinID"),Integer)
            End Get
            Set
                Me("Glock_18_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Faded")>  _
        Public Property Glock_18_SkinName() As String
            Get
                Return CType(Me("Glock_18_SkinName"),String)
            End Get
            Set
                Me("Glock_18_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("179")>  _
        Public Property Tec_9_SkinID() As Integer
            Get
                Return CType(Me("Tec_9_SkinID"),Integer)
            End Get
            Set
                Me("Tec_9_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Nuke")>  _
        Public Property Tec_9_SkinName() As String
            Get
                Return CType(Me("Tec_9_SkinName"),String)
            End Get
            Set
                Me("Tec_9_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("389")>  _
        Public Property P2000_SkinID() As Integer
            Get
                Return CType(Me("P2000_SkinID"),Integer)
            End Get
            Set
                Me("P2000_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Master of Fire")>  _
        Public Property P2000_SkinName() As String
            Get
                Return CType(Me("P2000_SkinName"),String)
            End Get
            Set
                Me("P2000_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("102")>  _
        Public Property P250_SkinID() As Integer
            Get
                Return CType(Me("P250_SkinID"),Integer)
            End Get
            Set
                Me("P250_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Void")>  _
        Public Property P250_SkinName() As String
            Get
                Return CType(Me("P250_SkinName"),String)
            End Get
            Set
                Me("P250_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("504")>  _
        Public Property USP_S_SkinID() As Integer
            Get
                Return CType(Me("USP_S_SkinID"),Integer)
            End Get
            Set
                Me("USP_S_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Headshot")>  _
        Public Property USP_S_SkinName() As String
            Get
                Return CType(Me("USP_S_SkinName"),String)
            End Get
            Set
                Me("USP_S_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("643")>  _
        Public Property CZ75_Auto_SkinID() As Integer
            Get
                Return CType(Me("CZ75_Auto_SkinID"),Integer)
            End Get
            Set
                Me("CZ75_Auto_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Drawtime over 9000")>  _
        Public Property CZ75_Auto_SkinName() As String
            Get
                Return CType(Me("CZ75_Auto_SkinName"),String)
            End Get
            Set
                Me("CZ75_Auto_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("522")>  _
        Public Property R8_Revolver_SkinID() As Integer
            Get
                Return CType(Me("R8_Revolver_SkinID"),Integer)
            End Get
            Set
                Me("R8_Revolver_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Faded")>  _
        Public Property R8_Revolver_SkinName() As String
            Get
                Return CType(Me("R8_Revolver_SkinName"),String)
            End Get
            Set
                Me("R8_Revolver_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("393")>  _
        Public Property XM1014_SkinID() As Integer
            Get
                Return CType(Me("XM1014_SkinID"),Integer)
            End Get
            Set
                Me("XM1014_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tranquility")>  _
        Public Property XM1014_SkinName() As String
            Get
                Return CType(Me("XM1014_SkinName"),String)
            End Get
            Set
                Me("XM1014_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("39")>  _
        Public Property MAG_7_SkinID() As Integer
            Get
                Return CType(Me("MAG_7_SkinID"),Integer)
            End Get
            Set
                Me("MAG_7_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Bulldozer")>  _
        Public Property MAG_7_SkinName() As String
            Get
                Return CType(Me("MAG_7_SkinName"),String)
            End Get
            Set
                Me("MAG_7_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("83")>  _
        Public Property Sawed_Off_SkinID() As Integer
            Get
                Return CType(Me("Sawed_Off_SkinID"),Integer)
            End Get
            Set
                Me("Sawed_Off_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Camo")>  _
        Public Property Sawed_Off_SkinName() As String
            Get
                Return CType(Me("Sawed_Off_SkinName"),String)
            End Get
            Set
                Me("Sawed_Off_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("537")>  _
        Public Property Nova_SkinID() As Integer
            Get
                Return CType(Me("Nova_SkinID"),Integer)
            End Get
            Set
                Me("Nova_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Beastmode")>  _
        Public Property Nova_SkinName() As String
            Get
                Return CType(Me("Nova_SkinName"),String)
            End Get
            Set
                Me("Nova_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("433")>  _
        Public Property MAC_10_SkinID() As Integer
            Get
                Return CType(Me("MAC_10_SkinID"),Integer)
            End Get
            Set
                Me("MAC_10_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Nightman")>  _
        Public Property MAC_10_SkinName() As String
            Get
                Return CType(Me("MAC_10_SkinName"),String)
            End Get
            Set
                Me("MAC_10_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("156")>  _
        Public Property P90_SkinID() As Integer
            Get
                Return CType(Me("P90_SkinID"),Integer)
            End Get
            Set
                Me("P90_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Nyan Cat")>  _
        Public Property P90_SkinName() As String
            Get
                Return CType(Me("P90_SkinName"),String)
            End Get
            Set
                Me("P90_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("556")>  _
        Public Property UMP_45_SkinID() As Integer
            Get
                Return CType(Me("UMP_45_SkinID"),Integer)
            End Get
            Set
                Me("UMP_45_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tiger")>  _
        Public Property UMP_45_SkinName() As String
            Get
                Return CType(Me("UMP_45_SkinName"),String)
            End Get
            Set
                Me("UMP_45_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("102")>  _
        Public Property MP7_SkinID() As Integer
            Get
                Return CType(Me("MP7_SkinID"),Integer)
            End Get
            Set
                Me("MP7_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Void")>  _
        Public Property MP7_SkinName() As String
            Get
                Return CType(Me("MP7_SkinName"),String)
            End Get
            Set
                Me("MP7_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("39")>  _
        Public Property MP9_SkinID() As Integer
            Get
                Return CType(Me("MP9_SkinID"),Integer)
            End Get
            Set
                Me("MP9_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Bulldozer")>  _
        Public Property MP9_SkinName() As String
            Get
                Return CType(Me("MP9_SkinName"),String)
            End Get
            Set
                Me("MP9_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
        Public Property AK_47_SkinID() As Integer
            Get
                Return CType(Me("AK_47_SkinID"),Integer)
            End Get
            Set
                Me("AK_47_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Revolution")>  _
        Public Property AK_47_SkinName() As String
            Get
                Return CType(Me("AK_47_SkinName"),String)
            End Get
            Set
                Me("AK_47_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("455")>  _
        Public Property AUG_SkinID() As Integer
            Get
                Return CType(Me("AUG_SkinID"),Integer)
            End Get
            Set
                Me("AUG_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Weeaboo Power")>  _
        Public Property AUG_SkinName() As String
            Get
                Return CType(Me("AUG_SkinName"),String)
            End Get
            Set
                Me("AUG_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("604")>  _
        Public Property FAMAS_SkinID() As Integer
            Get
                Return CType(Me("FAMAS_SkinID"),Integer)
            End Get
            Set
                Me("FAMAS_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RoadRage")>  _
        Public Property FAMAS_SkinName() As String
            Get
                Return CType(Me("FAMAS_SkinName"),String)
            End Get
            Set
                Me("FAMAS_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("661")>  _
        Public Property Galil_AR_SkinID() As Integer
            Get
                Return CType(Me("Galil_AR_SkinID"),Integer)
            End Get
            Set
                Me("Galil_AR_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Candyshop")>  _
        Public Property Galil_AR_SkinName() As String
            Get
                Return CType(Me("Galil_AR_SkinName"),String)
            End Get
            Set
                Me("Galil_AR_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("309")>  _
        Public Property M4A4_SkinID() As Integer
            Get
                Return CType(Me("M4A4_SkinID"),Integer)
            End Get
            Set
                Me("M4A4_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property M4A4_SkinName() As String
            Get
                Return CType(Me("M4A4_SkinName"),String)
            End Get
            Set
                Me("M4A4_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("487")>  _
        Public Property SG_553_SkinID() As Integer
            Get
                Return CType(Me("SG_553_SkinID"),Integer)
            End Get
            Set
                Me("SG_553_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SG_553_SkinName() As String
            Get
                Return CType(Me("SG_553_SkinName"),String)
            End Get
            Set
                Me("SG_553_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property M4A1_S_SkinID() As Integer
            Get
                Return CType(Me("M4A1_S_SkinID"),Integer)
            End Get
            Set
                Me("M4A1_S_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property M4A1_S_SkinName() As String
            Get
                Return CType(Me("M4A1_S_SkinName"),String)
            End Get
            Set
                Me("M4A1_S_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("344")>  _
        Public Property AWP_SkinID() As Integer
            Get
                Return CType(Me("AWP_SkinID"),Integer)
            End Get
            Set
                Me("AWP_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AWP_SkinName() As String
            Get
                Return CType(Me("AWP_SkinName"),String)
            End Get
            Set
                Me("AWP_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("493")>  _
        Public Property G3SG1_SkinID() As Integer
            Get
                Return CType(Me("G3SG1_SkinID"),Integer)
            End Get
            Set
                Me("G3SG1_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property G3SG1_SkinName() As String
            Get
                Return CType(Me("G3SG1_SkinName"),String)
            End Get
            Set
                Me("G3SG1_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("597")>  _
        Public Property SCAR_20_SkinID() As Integer
            Get
                Return CType(Me("SCAR_20_SkinID"),Integer)
            End Get
            Set
                Me("SCAR_20_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SCAR_20_SkinName() As String
            Get
                Return CType(Me("SCAR_20_SkinName"),String)
            End Get
            Set
                Me("SCAR_20_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("624")>  _
        Public Property SSG_08_SkinID() As Integer
            Get
                Return CType(Me("SSG_08_SkinID"),Integer)
            End Get
            Set
                Me("SSG_08_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SSG_08_SkinName() As String
            Get
                Return CType(Me("SSG_08_SkinName"),String)
            End Get
            Set
                Me("SSG_08_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("496")>  _
        Public Property M249_SkinID() As Integer
            Get
                Return CType(Me("M249_SkinID"),Integer)
            End Get
            Set
                Me("M249_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property M249_SkinName() As String
            Get
                Return CType(Me("M249_SkinName"),String)
            End Get
            Set
                Me("M249_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("514")>  _
        Public Property Negev_SkinID() As Integer
            Get
                Return CType(Me("Negev_SkinID"),Integer)
            End Get
            Set
                Me("Negev_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Negev_SkinName() As String
            Get
                Return CType(Me("Negev_SkinName"),String)
            End Get
            Set
                Me("Negev_SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("542")>  _
        Public Property PP_Bizon_SkinID() As Integer
            Get
                Return CType(Me("PP_Bizon_SkinID"),Integer)
            End Get
            Set
                Me("PP_Bizon_SkinID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Anubis")>  _
        Public Property PP_Bizon_SkinName() As String
            Get
                Return CType(Me("PP_Bizon_SkinName"),String)
            End Get
            Set
                Me("PP_Bizon_SkinName") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.FastLogin.My.MySettings
            Get
                Return Global.FastLogin.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
